# fly.toml app configuration file generated for holdingempresas on 2025-01-22T16:00:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'holdingempresas'
primary_region = 'eze'

[build]
# You can leave the build section empty if you're not explicitly specifying build options

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  SPRING_DATASOURCE_URL = "jdbc:mysql://MySqlHoldingContainer:3306/holdingDataBase"
  SPRING_DATASOURCE_USERNAME = "rootRai"
  SPRING_DATASOURCE_PASSWORD = "root"
  MYSQL_BIND_ADDRESS: "0.0.0.0"
